export const RECEIVE_TICKETS = 'RECEIVE_TICKETS'
export const ADD_TICKET = 'ADD_TICKET'
export const GET_TICKET = 'GET_TICKET'
export const GET_USER = 'GET_USER'
export const SHOW_ERROR = 'SHOW_ERROR'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
export const SET_BUYER = 'SET_BUYER'
export const GET_BUYER = 'GET_BUYER'
export const SET_INVOICE = 'SET_INVOICE'
export const GET_INVOICE = 'SET_INVOICE'

//CONST CREDIT CARD

export const GET_TOKEN_CARD = 'GET_TOKEN_CARD';
export const SET_TOKEN_CARD = 'SET_TOKEN_CARD';
export const SET_CARD = 'SET_CARD';
export const GET_CARD = 'GET_CARD';


//CONST USERS

export const SET_USER = 'SET_USER'

//CONST CHECKOUT

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

//CONST NUM TICKETS

export const SET_NUM_TICKETS = 'SET_NUM_TICKETS'
export const GET_NUM_TICKETS = 'GET_NUM_TICKETS'
export const TICKETS_BUY = 'TICKETS_BUY'

//CONST PAYMENT METHOD
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
export const EMPTY_CART = 'EMPTY_CART';